import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};
const ContactPage = () => {
    return (
        <div>
            ContactPage
        </div>
    );
}

export default ContactPage;
