import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};
const AboutPage = () => {
  return (
    <div>
      AboutPage
      {/* bu Page ga kirib bomidi Private Route          > "_about" <    */}
    </div>
  );
};

export default AboutPage;
